### ISSUE TITLE
Turrets receive spawn protection they cant ever loose

### ISSUE THREAD

**Issue by LadyAlekto** [IceRaptor/SpawnProtection#1]
There should be an excpetion to turrets receiving the portection

**Comment by IceRaptor** [comment]
This prohibition has been in place since 1.1.0 - see https://github.com/IceRaptor/SpawnProtection/blob/48ae8f15a8bb75d1f4bd6e769f32c1b85170c742/SpawnProtection/SpawnProtection/Helper/ProtectionHelper.cs#L45 and https://github.com/IceRaptor/SpawnProtection/blob/48ae8f15a8bb75d1f4bd6e769f32c1b85170c742/SpawnProtection/SpawnProtection/Helper/ProtectionHelper.cs#L59. If this occurs it should be defined in the logfile, since everything is logged at info level. Going to close this as without a log file showing the error I can't see how this could be happening through SpawnProtection.
